global:
  scrape_interval: 15s
  scrape_timeout: 3s
scrape_configs:
  - job_name: external.http
    static_configs:
      - targets: ['localhost:9113']
  - job_name: external.amqp
    static_configs:
      - targets: ['localhost:9419']
  - job_name: app.redis
    static_configs:
      - targets: ['localhost:9121']
  - job_name: app.server
    static_configs:
      - targets: ['localhost:9111']
  - job_name: app.worker
    static_configs:
      - targets: ['localhost:9112']