{
 "title": "App Server",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(app_duration_seconds_count[1m])",
     "legendFormat": "{{handler}} ({{job}})"
    },
    {
     "expr": "rate(app_incoming_num_total[1m])",
     "legendFormat": "produceIncoming ({{job}})"
    },
    {
     "expr": "rate(app_polling_num_total[1m])",
     "legendFormat": "consumePolling ({{job}})"
    },
    {
     "expr": "rate(app_reading_num_total[1m])",
     "legendFormat": "consumeReading ({{job}})"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " rate(app_duration_seconds_sum[1m]) / rate(app_duration_seconds_count[1m])",
     "legendFormat": "{{handler}} ({{job}})"
    }
   ]
  },
  { "title": "Quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Delivery Quality",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "app_duration_seconds{handler=\"handleDelivery\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Incoming Quality",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "app_duration_seconds{handler=\"handleIncoming\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Unread Quality",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "app_duration_seconds{handler=\"handleUnread\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Read Quality",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "app_duration_seconds{handler=\"handleRead\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  }
 ]
}