version: "3"
services:
  metrics.prometheus:
    user: ${METRICS_DATA_USER}
    image: prom/prometheus
    volumes:
      - ./metrics/prometheus.yaml:/conf/prometheus.yaml:ro
      - ./metrics/data/prometheus:/prometheus
    network_mode: host
    command: --config.file=/conf/prometheus.yaml
  metrics.grafana:
    user: ${METRICS_DATA_USER}
    image: grafana/grafana
    volumes:
      - ./metrics/data/grafana:/var/lib/grafana
    network_mode: host