version: "3"
services:
  metrics.prometheus:
    user: ${DATA_USER:-1000}
    image: prom/prometheus
    volumes:
      - ./metrics/prometheus.yaml:/conf/prometheus.yaml:ro
      - ../data/prometheus:/etc/prometheus
    command: --config.file=/conf/prometheus.yaml
    ports:
      - 9090:9090
  metrics.grafana:
    user: ${DATA_USER:-1000}
    image: grafana/grafana
    volumes:
      - ../data/grafana:/var/lib/grafana
    ports:
      - 3000:3000